global:
  scrape_interval: 4s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.1.10:8000"]

  - job_name: "opentelemetry"
    static_configs:
      - targets: ["192.168.1.10:9090"]
